language: rust
jobs:
  include:
    # formatting
    - rust: stable
      install:
        - rustup component add rustfmt
      script: cargo fmt --verbose -- --check
    # build
    - rust: stable
      script:
        - cd keyed_priority_queue
        - cargo build --release
    - rust: beta
      script:
        - cd keyed_priority_queue
        - cargo build --release
    - rust: nightly
      script:
        - cd keyed_priority_queue
        - cargo build --release
    # Check benches
    - rust: stable
      script:
        - cd keyed_priority_queue
        - cargo bench --no-run
    - rust: beta
      script:
        - cd keyed_priority_queue
        - cargo bench --no-run
    - rust: nightly
      script:
        - cd keyed_priority_queue
        - cargo bench --no-run
    # tests
    - rust: stable
      script:
        - cd keyed_priority_queue
        - cargo test --verbose
    - rust: beta
      script:
        - cd keyed_priority_queue
        - cargo test --verbose
    - rust: nightly
      script:
        - cd keyed_priority_queue
        - cargo test --verbose
    # Minimal supported rustc
    - rust: 1.56.0
      script:
        - cargo test --verbose
    # Unsafe soundness prove
    - rust: nightly-2021-10-23
      script:
        - rustup component add miri
        - cargo miri test -j16 --verbose --all-features
    # Validate readyness to publish
    - rust: stable
      script: 
        - cd keyed_priority_queue
        - cargo publish --dry-run

  allow_failures:
    - rust: nightly
    - rust: beta

notifications:
  email:
    on_success: never
