language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
    - rust: beta

install:
  - rustup component add rustfmt

script:
  - cargo build --release
  - cargo test --verbose
  - cargo fmt --verbose -- --check

notifications:
  email:
    on_success: never
